export const myProjects = [
  {
    projectTitle: "Modern Profile",
    category: ["Simple"],
    imgPath: "./images/Screenshot 2025-09-05 222801.png",
    link: "https://famous-swan-6e1bb4.netlify.app/",
    desc: `A modern developer portfolio built with Next.js, TypeScript, Tailwind CSS, and Aceternity UI.`,
    href: "https://github.com/mahmou9d/NextProfile",
  },
  {
    projectTitle: "Prime Ecom",
    category: ["Simple"],
    imgPath: "./images/Screenshot 2025-09-05 224742.png",
    link: "https://guileless-tiramisu-18d615.netlify.app/",
    desc: `E-commerce app built with React, Redux Toolkit & TypeScript — featuring product browsing, search, auth, cart, wishlist, and discounts.`,
    href: "https://github.com/mahmou9d/advancedE-commerce",
  },
  {
    projectTitle: "E-commerce",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-09-05 222413.png",
    link: "https://benevolent-beignet-116c19.netlify.app/",
    desc: `E-commerce landing page built with React & SCSS — responsive, dynamic UI with cart and localStorage.
`,
    href: "https://github.com/mahmou9d/ecommerces",
  },
  {
    projectTitle: "E-commerce",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-09-05 232737.png",
    link: "https://poetic-truffle-8702f4.netlify.app/",
    desc: `E-commerce landing page built with Next.js, TypeScript, Tailwind & Shadcn — responsive, dynamic UI with cart using Redux Toolkit and Stripe integration.`,
    href: "https://github.com/mahmou9d/super-store",
  },
  {
    projectTitle: "E-commerce",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-09-05 222730.png",
    link: "https://guileless-donut-c16f52.netlify.app/",
    desc: `Responsive e-commerce frontend built with React & Context API — featuring hero slider, category tabs, search, and cart with localStorage persistence.`,
    href: "https://github.com/mahmou9d/ecoo",
  },
  {
    projectTitle: "Dashboard",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-06-26 160415.png",
    link: "https://statuesque-conkies-a26f3f.netlify.app/",
    desc: `Modern React dashboard with responsive layout, charts (Nivo/Recharts), key stats, revenue graph, and transactions panel.`,
    href: "https://github.com/mahmou9d/dashboard",
  },
  {
    projectTitle: "CRUD APP",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-09-05 231543.png",
    link: "https://curd-mk8q.vercel.app/",
    desc: `React + Redux Toolkit CRUD app with real backend — add, view, read, and delete books. Form handled with React Hook Form & Yup.
`,
    href: "https://github.com/mahmou9d/curd",
  },
  {
    projectTitle: "Advanced Todolist",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-09-05 230324.png",
    link: "https://list-advanced.web.app",
    desc: `Task management app built with React & Context API — Arabic UI, CRUD tasks, filters, and localStorage persistence.`,
    href: "https://github.com/mahmou9d/todolist-advanced",
  },
  {
    projectTitle: "Weather APP",
    category: ["Simple"],
    imgPath: "./images/Screenshot 2025-04-23 180418.png",
    link: "https://peaceful-pothos-2d7a29.netlify.app",
    desc: `React weather app — shows real-time city, date, temperatures, condition & icon. Responsive UI, supports English & Arabic.
`,
    href: "https://github.com/mahmou9d/weather",
  },

  {
    projectTitle: "Landing Page",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-07-31 120310.png",
    desc: `Hero section built with React, SCSS & Framer Motion — gradient headline, benefits, email input, and smooth animations.`,
    link: "https://timely-florentine-bb449e.netlify.app/",
    href: "https://github.com/mahmou9d/React_Scss",
  },
];
//   {
//     projectTitle: "Profile",
//     category: ["Simple"],
//     imgPath: "./images/Screenshot 2025-07-31 144813.png",
//     link: "https://profile2-u8vk.vercel.app/",
//     desc: `Hero section using Next.js, Tailwind CSS, Shadcn UI, and Framer Motion.
// It includes a bold intro with the developer’s name, a short description, a “Download CV” button, social icons, and animated visuals. The layout is clean, responsive, and modern`,
//     href: "https://github.com/mahmou9d/profile2/tree/master",
//   },