export const myProjects = [
  {
    projectTitle: "Advanced Todolist",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-04-23 180322.png",
    link: "https://list-advanced.web.app",
    desc: "used: React and Redux and localstorage",
    href: "https://github.com/mahmou9d/todolist-advanced",
  },
  {
    projectTitle: "Simple ToDoList",
    category: ["Simple"],
    imgPath: "./images/Screenshot 2025-04-23 180359.png",
    link: "https://todolist-e8e08.web.app",
    desc: "used: React and localstorage",
    href: "https://github.com/mahmou9d/simple-ToDoList",
  },
  {
    projectTitle: "Weather APP",
    category: ["Simple"],
    imgPath: "./images/Screenshot 2025-04-23 180418.png",
    link: "https://peaceful-pothos-2d7a29.netlify.app",
    desc: "used: React and API",
    href: "https://github.com/mahmou9d/weather",
  },
  {
    projectTitle: "E-commerce",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-04-23 181444.png",
    link: "https://charming-eclair-8948ea.netlify.app",
    desc: "used: React and localstorage",
    href: "https://github.com/mahmou9d/ecommerces",
  },
  {
    projectTitle: "E-commerce",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-06-26 155943.png",
    link: "https://spontaneous-dusk-8c5b7a.netlify.app/",
    desc: "used: React and localstorage",
    href: "https://github.com/mahmou9d/ecoo",
  },
  {
    projectTitle: "CRUD APP",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-06-27 152649.png",
    link: "https://redux-edcc6.web.app/",
    desc: "used: React and ReduxToolkit",
    href: "https://github.com/mahmou9d/ReduxToolkit",
  },
  {
    projectTitle: "Dashboard",
    category: ["Complex"],
    imgPath: "./images/Screenshot 2025-06-26 160415.png",
    link: "https://statuesque-conkies-a26f3f.netlify.app/",
    desc: "used: React",
    href: "https://github.com/mahmou9d/ecommerces",
  },

  {
    projectTitle: "node project",
    category: ["Complex"],
    imgPath: "./images/8.jpg",
    desc: "used: React and Redux",
  },
  {
    projectTitle: "javaScript project",
    category: ["Complex"],
    imgPath: "./images/9.jpg",
    desc: "used: React and Redux",
  },
];
